### PR TITLE
shell for SECCON CTF QUALS 2016 plus one challenge

### PR DESCRIPTION
**Pull request by cseagle**

### CODE REVIEW

**Comment by m1ghtym0** [comment]
Oh dear, I haven't checked the PRs before adding Seccon CTF m)
I'm so sorry! If you want to, you can add further Information to the ropsynth challenge?
Was a nice challenge! Were you the author, or why do we owe the honor that you opened this PR?:-)

**Comment by cseagle** [comment]
I was not the author. A friend encouraged me to submit my solution and the related blobs that I downloaded so that they would be available to the CTF community.

**Comment by m1ghtym0** [comment]
I see, would be nice if you'd still be interested in adding those blobs to the repo.
Maybe just open another PR, or adjust this one. Again I'm really sorry I blew it!

**Comment by cseagle** [comment]
I'll sort it out and submit a new PR

**Comment by Amar1729** [comment]
was this issue ever resolved?

**Comment by m1ghtym0** [comment]
@Amar1729 Not yet nope

**Comment by dhanvi** [comment]
Please do a rebase and create a new PR

**Pull request closed without merging**
