### PR TITLE
Remove trailing empty entry

### PR DESCRIPTION
**Pull request by fbonzon**

### CODE REVIEW

**Comment by dhanvi** [comment]
@fbonzon are you testing how Pull Requests work ? it doesn't makes sence to add a new empty line

**Comment by fbonzon** [comment]
No, I'm not. I removed here the trailing empty entry inadvertently added a few minutes before.

**Comment by fbonzon** [comment]
You can re-open and apply. Sorry, I was not clear before :)

**Comment by dhanvi** [comment]
deleting a new line is not worth a commit :-1: 

may be we can reuse it next time :)

**Comment by dhanvi** [comment]
Thanks for the PR @fbonzon

**Comment by dhanvi** [comment]
I have changed my mind :) 

I thought it was a empty line with nothing, but it was having a bullet point which is kind of annoying :+1: 

Hope to see more contributions from you @fbonzon

**Pull request merged**
