### PR TITLE
Added writeups

### PR DESCRIPTION
**Pull request by kablaa**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Can you update the CTFs main README moving the lolcpp-250 challenge link from the missing section to the external only section? You can put `* none yet` under the missing section as a placeholder. Otherwise looks good. https://github.com/ctfs/write-ups-2016/blob/master/tum-ctf-2016/README.md

**Comment by kablaa** [comment]
updated the CTFs main README

**Review by ghost — CHANGES_REQUESTED** [review]
Don't forget to use 'none yet' instead of 'none'.

**Comment by kablaa** [comment]
changed none not none yet

**Comment by m1ghtym0** [comment]
thanks \o/

**Pull request merged**
