### PR TITLE
:link: Added external write-up link

### PR DESCRIPTION
**Pull request by bananaappletw**

### CODE REVIEW

**Comment by bananaappletw** [comment]
Sorry, I failed to let emoji working properly.

**Comment by abpolym** [comment]
@bananaappletw  I am sorry to inform you that failing to add a emoji requires you to perform seppuku without any hesitation.

**Comment by bananaappletw** [comment]
Ha ha, I see.
Thank you for the explanation.

**Comment by abpolym** [comment]
@bananaappletw Also I think you changed only the title of the Issue, but not the commit message - so thats why it didn't change there - two different things :)

**Pull request merged**
