### PR TITLE
Adding all writeups from 0x90r00t done so far

### PR DESCRIPTION
**Pull request by Laxa**

### CODE REVIEW

**Comment by Laxa** [comment]
I remark that adding write-ups on ctftime will be added on this repo so should I still PR for them ?

**Comment by dhanvi** [comment]
@Laxa Thanks for adding the links :+1: 

Yes we do add the writeups from ctftime.org

PR is always welcome as it reduces the work from our side, if you have already submitted the writeup to ctftime.org it will be mentioned in the issues by @write-ups-bot 

If you want to contribute to this repo feel free to create a PR and mention the issue to close so that we don't do the work twice

**Comment by Laxa** [comment]
I'll do that in the future :).
I commented on all issue that you can close with this PR.

**Comment by YASME-Tim** [comment]
Cool, thanks for the work @Laxa :) - will have a look at the issues and close them later

**Pull request merged**
